### ISSUE TITLE
Test suite against live droplet

### ISSUE THREAD

**Issue by sckott** [pachadotdev/analogsea#104]
Would be painfully slow to run tests against a real droplet, but I'll play with this for separate testing via `test_dir()` - to allow anyone with a DO acct to run them

**Comment by pachadotdev** [comment]
this has been added since I was assigned as the new maintainer

the current tests:

1. create droplets
2. install R and R packages in droplets
3. remove droplets
4. all on GH-actions, with proper tokens and oauth
