### ISSUE TITLE
"Error: Please install ssh" from ubuntu_create_user

### ISSUE THREAD

**Issue by aetiologicCanada** [pachadotdev/analogsea#209]
This code below works, but ubuntu_create_user() fails with a "please install ssh" error.
 
Am I missing something?  Should I adding arguments to droplet_create to generate ssh?  

Thanks,

R

``

library(tidyverse)
library(analogsea)
#analogsea::account()
do_pat="******************"
Sys.setenv("DO_PAT" = do_pat)
droplets()
# droplet_create(
#   name = "testing",
#   ssh_keys = "/home/rob/.ssh/id_rsa",user_data = "/home/rob/test.txt"
# ) -> details

droplet_create("rstudio-20-04", 
               ssh_keys = '~/.ssh/id_rsa.pub')

ubuntu_create_user("rstudio-20-04", 
                   "rob", 
                   "rob_password", 
                   keyfile = "~/.ssh/id_rsa")

 
--

**Comment by pachadotdev** [comment]
sorry for the delay
for future reference: you need install.packages("ssh")
