### ISSUE TITLE
Install packages from bitbucket

### ISSUE THREAD

**Issue by MislavSag** [pachadotdev/analogsea#216]
I want to install package from bitbucket: https://bitbucket.org/quanttools/quanttools/src/master/

I know how to install packages from CRAN or GitHub, for example
```r
analogsea::install_r_package(droplet_id, "data.table")
```
but can't figure oput how to install QuantTools from birbucket.

**Comment by MislavSag** [comment]
I have an additional question. Is it possible to restrict dependency installation when installing packages from github?

**Comment by pachadotdev** [comment]
Hi
I don't have a method for bitbucket at the moment. What you can do is to clone the repository in your server and install with devtools.
Regarding restrictions, that's not possible. analogsea uses remotes (package) to install from GitHub.

**Comment by MislavSag** [comment]
I have solve the problem by adding the package in one of my pachages (Remotes: bitbucket::test/test).
Thanks for help.
