### ISSUE TITLE
Unable to authenticate you

### ISSUE THREAD

**Issue by jzadra** [pachadotdev/analogsea#219]
I am getting "Error: Unable to authenticate you" for just about every function.

I have DO_PAT = "{my pat}" set in my .Renviron.  I am able to access my buckets using aws.s3 and the same credentials.  However, aws.s3 package also has an environment variable for my secret key.

Are there additional environmental variables that need to be set?  I'm not finding any documentation beyond the DO_PAT for variables.

I'm also not seeing a way to manually supply the PAT and SECRET to the analogsea functions - is this possible?

**Comment by pachadotdev** [comment]
HI @jzadra. We have a conflict with a dependency that we are trying to fix. I'll get back to you this Monday.

**Comment by pachadotdev** [comment]
also, you only need the DO_PAT
I just run the tests in the CI again, I hope to have fixed the SSH auth issue

**Comment by pachadotdev** [comment]
@jzadra also important, are you using a non-standard name for your SSH key?

**Comment by jzadra** [comment]
I'm not using an SSH key actually, and I've had success accessing my buckets using aws.s3 without it.
